{
  "stats": {
    "suites": 4,
    "tests": 9,
    "passes": 0,
    "pending": 0,
    "failures": 9,
    "start": "2024-03-07T16:09:17.176Z",
    "end": "2024-03-07T16:09:19.481Z",
    "duration": 2305,
    "testsRegistered": 9,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "6155dcbe-cba7-4071-b7f8-79b7b065d683",
      "title": "",
      "fullFile": "cypress/e2e/App.cy.js",
      "file": "cypress/e2e/App.cy.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [],
      "suites": [
        {
          "uuid": "23581c1c-8ea0-4276-8df1-0494fd5c3978",
          "title": "1 - Crie as rotas para a aplicação",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "Ao entrar na rota / é renderizado apenas o componente <Users />",
              "fullTitle": "1 - Crie as rotas para a aplicação Ao entrar na rota / é renderizado apenas o componente <Users />",
              "timedOut": null,
              "duration": 329,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "setup();\ncy.get('[data-testid=\"users-page\"]').should('exist');\ncy.get('[data-testid$=\"-page\"]').should('have.length', 1);",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "fe552f97-3a16-4db8-bad6-0321aa67456c",
              "parentUUID": "23581c1c-8ea0-4276-8df1-0494fd5c3978",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "Ao entrar na rota /about é renderizado apenas o componente <About />",
              "fullTitle": "1 - Crie as rotas para a aplicação Ao entrar na rota /about é renderizado apenas o componente <About />",
              "timedOut": null,
              "duration": 154,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "setup('about');\ncy.get('[data-testid=\"about-page\"]').should('exist');\ncy.get('[data-testid$=\"-page\"]').should('have.length', 1);",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "df41cb21-d47d-44ed-9aec-db453fc224bf",
              "parentUUID": "23581c1c-8ea0-4276-8df1-0494fd5c3978",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "Ao entrar na rota /posts é renderizado apenas o componente <Posts />",
              "fullTitle": "1 - Crie as rotas para a aplicação Ao entrar na rota /posts é renderizado apenas o componente <Posts />",
              "timedOut": null,
              "duration": 110,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "setup('posts/id');\ncy.get('[data-testid=\"posts-page\"]').should('exist');\ncy.get('[data-testid$=\"-page\"]').should('have.length', 1);",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "c948f12c-83ab-4282-bd26-c8ceec9103d8",
              "parentUUID": "23581c1c-8ea0-4276-8df1-0494fd5c3978",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "Ao entrar em uma rota não existente é renderizado o componente <NotFound />",
              "fullTitle": "1 - Crie as rotas para a aplicação Ao entrar em uma rota não existente é renderizado o componente <NotFound />",
              "timedOut": null,
              "duration": 100,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "setup('not-found');\ncy.get('[data-testid=\"not-found-page\"]').should('exist');\ncy.get('[data-testid$=\"-page\"]').should('have.length', 1);",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "c9b9c667-1bbc-467a-926b-171094ad09c5",
              "parentUUID": "23581c1c-8ea0-4276-8df1-0494fd5c3978",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "fe552f97-3a16-4db8-bad6-0321aa67456c",
            "df41cb21-d47d-44ed-9aec-db453fc224bf",
            "c948f12c-83ab-4282-bd26-c8ceec9103d8",
            "c9b9c667-1bbc-467a-926b-171094ad09c5"
          ],
          "pending": [],
          "skipped": [],
          "duration": 693,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        },
        {
          "uuid": "c4a5f5f9-561e-4cab-9893-67b9fb11d1a9",
          "title": "2- Crie dois NavLink dentro do componente Header",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "O primeiro NavLink deve possuir o texto \"Home\" e a rota \"/\"",
              "fullTitle": "2- Crie dois NavLink dentro do componente Header O primeiro NavLink deve possuir o texto \"Home\" e a rota \"/\"",
              "timedOut": null,
              "duration": 103,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.get('a').contains(/home/i).should('have.attr', 'href', '/');",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "c8860f61-62d1-4109-b3a0-f16959a5faff",
              "parentUUID": "c4a5f5f9-561e-4cab-9893-67b9fb11d1a9",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "O segundo NavLink deve possuir o texto \"About\" e a rota \"/about\"",
              "fullTitle": "2- Crie dois NavLink dentro do componente Header O segundo NavLink deve possuir o texto \"About\" e a rota \"/about\"",
              "timedOut": null,
              "duration": 99,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "cy.get('a').contains(/about/i).should('have.attr', 'href', '/about');",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "846cfa6d-c595-497c-b16f-63289dcfe2c8",
              "parentUUID": "c4a5f5f9-561e-4cab-9893-67b9fb11d1a9",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "c8860f61-62d1-4109-b3a0-f16959a5faff",
            "846cfa6d-c595-497c-b16f-63289dcfe2c8"
          ],
          "pending": [],
          "skipped": [],
          "duration": 202,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        },
        {
          "uuid": "02b3d481-23e9-4157-9e8b-492fd7aad6f5",
          "title": "3 - Crie um link para a página de posts de um usuário",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "O link deve possuir o texto \"Posts\" e a rota \"/posts/id\"",
              "fullTitle": "3 - Crie um link para a página de posts de um usuário O link deve possuir o texto \"Posts\" e a rota \"/posts/id\"",
              "timedOut": null,
              "duration": 97,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "for (let id = 1; id <= _data.users.length; id++) {\n  cy.get(`a[href=\"/posts/${id}\"]`).should('exist');\n}",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "4b287816-b6ad-4ee5-be72-03adc76842cd",
              "parentUUID": "02b3d481-23e9-4157-9e8b-492fd7aad6f5",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "4b287816-b6ad-4ee5-be72-03adc76842cd"
          ],
          "pending": [],
          "skipped": [],
          "duration": 97,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        },
        {
          "uuid": "d59fa93a-025c-4392-a248-82b180b903bf",
          "title": "4 - Exiba os posts de um usuário",
          "fullFile": "",
          "file": "",
          "beforeHooks": [],
          "afterHooks": [],
          "tests": [
            {
              "title": "O componente <Posts /> deve renderizar apenas os posts do primeiro usuário",
              "fullTitle": "4 - Exiba os posts de um usuário O componente <Posts /> deve renderizar apenas os posts do primeiro usuário",
              "timedOut": null,
              "duration": 101,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "setup('posts/1');\nconst othersPosts = _data.posts.filter(post => post.userId !== 1);\nothersPosts.forEach(post => {\n  cy.get('h2').should('not.contain', post.title);\n});\nconst userPosts = _data.posts.filter(post => post.userId === 1);\nuserPosts.forEach(post => {\n  cy.contains(post.title);\n});",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "22806124-f4b9-4cdd-b354-a07a683cfd2b",
              "parentUUID": "d59fa93a-025c-4392-a248-82b180b903bf",
              "isHook": false,
              "skipped": false
            },
            {
              "title": "O componente <Posts /> deve renderizar os posts do usuário",
              "fullTitle": "4 - Exiba os posts de um usuário O componente <Posts /> deve renderizar os posts do usuário",
              "timedOut": null,
              "duration": 99,
              "state": "failed",
              "speed": null,
              "pass": false,
              "fail": true,
              "pending": false,
              "context": null,
              "code": "_data.users.forEach(user => {\n  setup(`posts/${user.id}`);\n  const userPosts = _data.posts.filter(post => post.userId === user.id);\n  userPosts.forEach(post => {\n    cy.contains(post.title);\n  });\n});",
              "err": {
                "message": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application",
                "estack": "Error: The following error originated from your application code, not from Cypress.\n\n  > You cannot render a <Router> inside another <Router>. You should never have more than one in your app.\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at invariant (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:207:11)\n    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=937d5a86:3932:35)\n    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:12169:26)\n    at mountIndeterminateComponent (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:14919:21)\n    at beginWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:15900:22)\n    at HTMLUnknownElement.callCallback2 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3672:22)\n    at Object.invokeGuardedCallbackDev (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3697:24)\n    at invokeGuardedCallback (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:3731:39)\n    at beginWork$1 (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19759:15)\n    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/chunk-MMW4JUSU.js?v=459b3375:19192:20)",
                "diff": null
              },
              "uuid": "d3171256-cd79-4e25-a3c9-82b832f6dc6e",
              "parentUUID": "d59fa93a-025c-4392-a248-82b180b903bf",
              "isHook": false,
              "skipped": false
            }
          ],
          "suites": [],
          "passes": [],
          "failures": [
            "22806124-f4b9-4cdd-b354-a07a683cfd2b",
            "d3171256-cd79-4e25-a3c9-82b832f6dc6e"
          ],
          "pending": [],
          "skipped": [],
          "duration": 200,
          "root": false,
          "rootEmpty": false,
          "_timeout": 2000
        }
      ],
      "passes": [],
      "failures": [],
      "pending": [],
      "skipped": [],
      "duration": 0,
      "root": true,
      "rootEmpty": true,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "id": "default",
        "reportDir": "cypress/reports",
        "overwrite": false,
        "html": false,
        "json": true
      },
      "version": "6.2.0"
    }
  }
}